apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: $KYML_APP_NAME
  namespace: $KYML_NAMESPACE
spec:
  default:
    timeoutSec: 60
    connectionDraining:
      drainingTimeoutSec: 60
  targetRef:
    group: ""
    kind: Service
    name: $KYML_APP_NAME


---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: $KYML_APP_NAME
  namespace: $KYML_NAMESPACE
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: GRPC
      grpcHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: $KYML_GRPC_PORT_NUMBER
  targetRef:
    group: ""
    kind: Service
    name: $KYML_APP_NAME
