apiVersion: v1
kind: Service
metadata:
  name: $KYML_APP_NAME
  namespace: $KYML_NAMESPACE
spec:
  type: ClusterIP
  selector:
    app: $KYML_APP_NAME
  ports:
    - name: $KYML_HTTP_PORT_NAME
      port: $KYML_HTTP_PORT_NUMBER
      targetPort: $KYML_HTTP_PORT_NUMBER
      appProtocol: http